# Generated by Django 4.0.6 on 2022-08-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shopcart_cart_code_shopcart_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='cart_code',
            field=models.CharField(max_length=255),
        ),
    ]
