# Generated by Django 4.0.6 on 2022-09-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_payment_address_payment_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='c_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shopcart',
            name='c_item',
            field=models.IntegerField(default='1'),
        ),
    ]
