# Generated by Django 4.0.6 on 2022-08-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('drink', models.BooleanField(default=False)),
                ('appetiser', models.BooleanField(default=False)),
                ('dessert', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='food')),
                ('price', models.IntegerField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('in_stock', models.BooleanField()),
                ('description', models.TextField(default='a')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techbro.category')),
            ],
        ),
    ]
