# Generated by Django 4.0.6 on 2022-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbro', '0004_dish_showcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=50)),
                ('show_txt', models.CharField(max_length=250)),
                ('show_img', models.ImageField(default='show.png', upload_to='showcase')),
            ],
            options={
                'verbose_name': 'showcase',
                'verbose_name_plural': 'showcases',
                'db_table': 'showcase',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'managed': True, 'verbose_name': 'Dish', 'verbose_name_plural': 'Dishes'},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='showcase',
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default='pix.png', null=True, upload_to='food'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
    ]
